name: NuGet Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup
        uses: actions/setup-dotnet@main
      - name: Pack
        run: dotnet build --configuration Release
      - name: Push
        run: dotnet nuget push .\bin\Release\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NuGetAPIKey }} --skip-duplicate --no-symbols 1
